architectures: amd64
debug: true
distribution: sid
donateUrl: https://www.debian.org
email: email@risserlabs.com
issuesUrl: https://bugs.debian.org
keyboardLayout: us
locale: en_US
mirror: http://deb.debian.org/debian/
mirrorSecurity: http://security.debian.org/
name: DEB Distro
releaseNotesUrl: https://www.debian.org/releases/bullseye/releasenotes
shortName: Debian
supportUrl: https://www.debian.org/support
version: 12
website: https://risserlabs.com
lb:
  debianInstaller: netinst # live,netinst
  debianInstallerGui: false
  debianInstallerDistribution: daily
overlays:
  # example: {}
  debianInstaller: {}
  firmware: {}
  grub: {}
  plymouth: {}
  sway: {}
  ungoogledChromium: {}
  tools: {}
  dev: {}
  gnome: {}
  flatpak:
    flatpaks:
      - https://dl.flathub.org/repo/appstream/me.iepure.devtoolbox.flatpakref
  snap:
    snaps:
      - yq
