name: Debian GNU/Linux
shortName: Debian
version: 11
supportUrl: https://www.debian.org/support
releaseNotesUrl: https://www.debian.org/releases/bullseye/releasenotes
issuesUrl: https://bugs.debian.org
donateUrl: https://www.debian.org
distribution: bullseye
architectures: amd64
email: email@bitspur.com
keyboardLayout: us
locale: en_US
mirror: http://deb.debian.org/debian/
mirrorSecurity: http://security.debian.org/
website: https://debian.org
overlays:
  # brave: {}
  calamares: {}
  sway: {}
  grub: {}
