name: Jam OS
version: 18.04
paths:
  iso: ubuntu-18.04-server-amd64.iso
  output: jam-os.iso
packages:
  - arandr
  - blueman
  - compton
  - cowsay
  - cups
  - dbus-x11
  - feh
  - fortune
  - gucharmap
  - i3
  - i3lock-color
  - lolcat
  - lxappearance
  - network-manager
  - network-manager-gnome
  - pavucontrol
  - playonlinux
  - python-pip
  - ranger
  - shutter
  - stow
  - system-config-printer
  - terminator
  - x11-apps
  - xbacklight
  - xinit
  - xsel
  - zsh
