name: Jam OS
version: 18.04
paths:
  iso: ubuntu-18.04-server-amd64.iso
  output: jam-os.iso
packages:
  - arandr
  - blueman
  - cbatticon
  - compton
  - cowsay
  - cups
  - dbus-x11
  - feh
  - fluxgui
  - fortune
  - gedit
  - gnome-power-manager
  - gparted
  - gucharmap
  - hardinfo
  - i3
  - i3lock-color
  - ispell
  - lolcat
  - lxappearance
  - ncdu
  - network-manager
  - network-manager-gnome
  - network-manager-openvpn-gnome
  - network-manager-pptp-gnome
  - pavucontrol
  - playonlinux
  - python-pip
  - ranger
  - seahorse
  - shutter
  - silversearcher-ag
  - stow
  - system-config-printer
  - terminator
  - x11-apps
  - xbacklight
  - xinit
  - xsel
  - zsh
