name: Jam OS
version: 18.04
paths:
  iso: ubuntu-18.04-server-amd64.iso
  output: jam-os.iso
packages:
  - blueman
  - cowsay
  - dbus-x11
  - feh
  - fortune
  - i3
  - lxappearance
  - network-manager
  - network-manager-gnome
  - ranger
  - shutter
  - terminator
  - xinit
